[project]
name = "images2pptx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow",
    "python-pptx",
    "pytesseract",
    "pyyaml",
    "logging>=0.4.9.6",
]
